# syntax=docker/dockerfile:1
FROM tiangolo/uvicorn-gunicorn:python3.11
ENV shm_size=2gb
WORKDIR /code

COPY *.txt *.py *.env .

# Add Microsoft SQL Server repository explicitly for Debian 'bookworm'
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    echo "deb [arch=amd64] https://packages.microsoft.com/debian/12/prod bookworm main" > /etc/apt/sources.list.d/mssql-release.list

# Install ODBC Driver 17
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17
RUN apt-get update && apt-get install -y \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
#   libgtk-4-1 \
    libnspr4 \
    libnss3 \
    libwayland-client0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    libu2f-udev \
    libvulkan1 \
	azure-cli
	
RUN pip install --no-cache-dir --upgrade -r requirements.txt

#COPY . .
RUN python -m nltk.downloader punkt
RUN python -m nltk.downloader punkt_tab
RUN python -m nltk.downloader averaged_perceptron_tagger_eng
# Chrome instalation 
RUN curl -LO  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# RUN apt-get install -y ./google-chrome-stable_current_amd64.deb
# RUN rm google-chrome-stable_current_amd64.deb
# Check chrome version
#RUN echo "Chrome: " && google-chrome --version

RUN apt-get install -y tesseract-ocr
RUN apt-get install poppler-utils -y
RUN playwright install

#RUN mkdir -p /home/DE_ChromaDB
#RUN mkdir -p /home/uploaded
#RUN mkdir -p /home/chathistory

EXPOSE 3100

CMD ["gunicorn", "digitaleye_api:app", "--timeout", "600", "--bind", "0.0.0.0:3100", "--workers","4", "--worker-class", "uvicorn.workers.UvicornWorker"]